### ISSUE TITLE
use numpy binaries on travis

### ISSUE THREAD

**Issue by borismarin** [OpenSourceBrain/osb-model-validation#47]
We don't need to waste time compiling numpy (and potentially scipy / sympy, see #46) on travis, since we can apt-get install it. This needs to be done for all .travis.yml, though -- so it would be nice to use the OSB api to fetch all projects and rewrite those files for us.

**Comment by JustasB** [comment]
I had similar problems installing numpy locally. Had to install numpy manually to get the dependencies to work.

**Comment by borismarin** [comment]
@JustasB see the conda branch, all that should be irrelevant given that we (will) have binaries for all deps.

**Comment by pgleeson** [comment]
Better support for numpy etc in travis now
