### ISSUE TITLE
omv all fails due to equal timestamps on OSX

### ISSUE THREAD

**Issue by borismarin** [OpenSourceBrain/osb-model-validation#51]
when `omv all` is run in a directory containing a dry-run test and a file-based test (e.g. spikes) for **the same target simulation**, the `ERROR! Preexistent datafile` will potentially pop out if the dry run produces the datafile expected by the file-based test. This usually happens OSX, where the timestamp for file modification has a resolution of 1s, if both runs finish faster than that.

Not doing anything for the moment, as it only affects trivial examples (very fast simulator/ion), on OSX.

**Comment by pgleeson** [comment]
No longer an issue with fix above
