### ISSUE TITLE
Add pyNeuroML as an engine

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/osb-model-validation#61]
This could be added already here: https://github.com/OpenSourceBrain/osb-model-validation/tree/master/omv/engines, but would be a bit superfluous, as it would give identical results to jNeuroML.

Nevertheless it would be a good test that pyNeuroML could be installed in a standard way, and that it can load all the models jnml can.

**Comment by usama57** [comment]
@pgleeson  pyNeuroML is also not in engine list. I installed pyNeuroML through git,i supposed to add same like neuroConstruct and after that chech omt test.

**Comment by pgleeson** [comment]
Yes, you'll need a pyneuroml_.py (underscore is to avoid naming conflicts with main pyneuroml package) and getpyneuroml.py. You should be able to add tests for any of the examples that are run with jnml.

**Comment by usama57** [comment]
The path for jnml is in "p = os.path.join(home, 'jnml/jNeuroMLJar')",  but for the pynml is that test.sh in pyNeuroML ?

**Comment by usama57** [comment]
I uploaded the files of pyneuroml_.py and  getpyneuroml.py. The test files are running locally with pynml and the file name but it is not working with omv test .test.pyneuroml.omt.

**Comment by pgleeson** [comment]
@usama57 I see you have two forks of the project: https://github.com/OpenSourceBrain/osb-model-validation/network. You need to make sure all your changes are on one which has all the latest updates from the master branch. You could try merging master to your master branch, but it might be easier to copy over your changes to the travislearning fork

**Comment by usama57** [comment]
@pgleeson  build status is still failled.

**Comment by pgleeson** [comment]
@usama57 you are cloning the repo in getpyneuroml.py but you need to do a "python setup.py install" also.

**Comment by usama57** [comment]
@pgleeson alright sir, and what about the rest of files. Is that ok ?

**Comment by usama57** [comment]
@pgleeson  kindly check it now. https://github.com/travislearning/osb-model-validation

**Comment by pgleeson** [comment]
I merged your changes here: https://github.com/OpenSourceBrain/osb-model-validation/compare/test_usama57 and made a few updates and now all the tests are passing. I'll have another look and merge the changes into master on Monday. Thanks.

**Comment by usama57** [comment]
@pgleeson  Alright Sir. Thanks
