### ISSUE TITLE
Add engine jNeuroML_Brian2

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/osb-model-validation#62]

**Comment by usama57** [comment]
@pgleeson  kidly guide me how to add first jNeuroML_Brian2 in the list of engines. I tried by adding method  in to omv_util.py, but it is not working. i also added engine too in _intit_.py.

**Comment by usama57** [comment]
@pgleeson  I think that for this task i just need to add another jneuromlbrian2.py file in engine and copy the data of jneuromlbrian.py file and set it accordingly to brian2 then  import it into _init_.py.

**Comment by pgleeson** [comment]
Yes, something long those lines. Make the changes locally, test them, commit them to your fork and I'll have a look. Try adding your fork for of this repo to Travis so the tests can be run there on your fork as you push. You'll have to add an example to the tests folder and the jNeuroML_Brian2 engine to .travis.yml

**Comment by usama57** [comment]
yeah i did on travis, build status is passing. i uploaded the files for jNeuroML_Brian2
