### ISSUE TITLE
Test failing when no spikes are expected

### ISSUE THREAD

**Issue by RokasSt** [OpenSourceBrain/osb-model-validation#65]
When expected spike times are [] and observed spikes are [] the omv test is still failing

**Comment by borismarin** [comment]
If no spikes are expected, why use the spike analyser? There is one for
rest state, see
https://github.com/borismarin/hh-testing/blob/master/NeuroML2/hh.lems.nostim.omt
On 7 Dec 2015 11:17, "RokasSt" <notifications@github.com> wrote:

When expected spike times are [] and observed spikes are [] the omv test is
still failing

—
Reply to this email directly or view it on GitHub
<https://github.com/OpenSourceBrain/osb-model-validation/issues/65>.

**Comment by RokasSt** [comment]
Thanks, it works @borismarin

**Comment by borismarin** [comment]
will make it pass for no spike times for consistency, though.

**Comment by RokasSt** [comment]
Well, it probably makes sense for the cases when some manipulation in the model parameters abolishes spike generation, while in the default state spikes are produced and thus expected.

**Comment by borismarin** [comment]
Even so, testing for rest state brings more information (unless you have
e.g. subthreshold oscillations).
Saying "I don't expect any spikes" is less informative and useful than "I
expect rest at -60mV". You can e.g. be missing spikes due to problems in
detection.

**Comment by RokasSt** [comment]
I see your point. For the cases I needed I had subthreshold oscillations

**Comment by borismarin** [comment]
In that case you might want to test for the frequency of subthreshold
oscillations. This still needs to be implemented, see
https://github.com/OpenSourceBrain/osb-model-validation/issues/4 . It
should be trivial, basically leveraging the spike detectors and analysing
isis. Feel free to contribute.
