### ISSUE TITLE
Add neuroConstruct_.py in engine

### ISSUE THREAD

**Issue by usama57** [OpenSourceBrain/osb-model-validation#67]
Which .py file or methods  should be import to add new engine in engine, second what would be the path for the neuroConstruct.py file,first would be the home path and how to set usr/local .. !

**Comment by pgleeson** [comment]
@usama57 I've added a nC project to the repo here: https://github.com/OpenSourceBrain/osb-model-validation/tree/master/utilities/tests/TestProject as well as some scripts here: https://github.com/OpenSourceBrain/osb-model-validation/tree/master/utilities/tests/TestProject/pythonScripts which you should be able to run locally with:

    nC.sh -python CheckProject.py

if you have the install path for nC added to PATH. I've added skeleton engine/install scripts here: https://github.com/OpenSourceBrain/osb-model-validation/tree/master/omv/engines to get you started.

**Comment by usama57** [comment]
@pgleeson  nC.sh -python CheckProject.py is running. I am trying to run .test.check.omt  by adding the location of neuroConstruct in first getneuroconstruct.py and writing the file of pyneuroconstruct.py but it is still giving error  "Failed due to non passing tests". I tried to run also by adding method into omv_util.py.

**Comment by usama57** [comment]
Its running now thank you for your support :+1:

**Comment by pgleeson** [comment]
Complete
