### ISSUE TITLE
Update to latest NEURON

### ISSUE THREAD

**Issue by salvadord** [OpenSourceBrain/osb-model-validation#71]
@pgleeson any plans to test with latest NEURON (VERSION 7.6.1crxd) available here: https://github.com/neuronsimulator/nrn

I forked this repo and tried to update it but getting an error in the ./configure -- see https://github.com/Neurosim-lab/osb-model-validation/blob/master/omv/engines/getnrn.py#L17

**Comment by pgleeson** [comment]
I've not tested yet with NEURON v7.6, mainly locally with 7.5, and use 7.4 on OMV tests. I should test 7.6 locally at some point, but in a way, it's better to test these online with an earlier version to make sure that anyone with that earlier version can run the models successfully... I'm fairly sure that the latest versions of nrn would behave identically to earlier versions for models within the scope of the older simulator...

As long as you have your preferred version of NRN installed locally and hooked up to Python, then the OMV tests should run for you. That install method is only called if it doesn't find Neuron.

**Comment by salvadord** [comment]
thanks Padraig -- I'm using this for Travis. As you say, we can probably assume 7.6 will behave identically as 7.5, but would be good to test eventually (also 7.6 has some new rxd features that netpyne might need to use soon).

**Comment by pgleeson** [comment]
@salvadord Many of the simulators now can have the specific version specified in the .travis.yml file, e.g. https://github.com/OpenSourceBrain/osb-model-validation/blob/master/.travis.yml

    - OMV_ENGINE=Brian2:2.2.2.1
    - OMV_ENGINE=NEST:2.14.0
    - OMV_ENGINE=NEURON:7.5
    - OMV_ENGINE=PyNEURON:7.6

As long as the URL for getting zip files for the simulators doesn't change they should be compatible/testable with future versions. 

Default version for NEURON is still 7.4. Info on all versions can be found in travis or locally by typing `omv find -V`. I'll close this issue when the default version of Nrn is updated.

**Comment by pgleeson** [comment]
Updated to Neuron 7.6, but any (future) version of NEURON can be selected with a line like:

    - OMV_ENGINE=NEURON:7.7
